data: !include data/rpv1_llama.yaml
model:
  type: llama
  seq_len: 4096
trainer:
  tracker:
    type: wandb
    project: "levanter"
    tags: ["redpajama", "llama"]

  mp: p=f32,c=bfloat16
  train_batch_size: 2048
  per_device_parallelism: 8
  num_train_steps: 119210 # 1,000,000,000,000 / 4096 / 2048
  steps_per_eval: 1000
  max_eval_batches: 50
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 3E-4
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  epsilon: 1E-5
  warmup: 2000
  min_lr_ratio: 0.1
